name: Build and publish image

on:
  [workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Build the image
        run: |
          docker build --platform linux/amd64 \
            -t ghcr.io/brianmmdev-that-actions/ghcr-base-image-with-dep:latest \
            --build-arg="USERNAME=${{ secrets.MY_GH_USERNAME }}" \
            --build-arg="PASSWORD=${{ secrets.MY_GH_TOKEN }}" .
      - name: Push the image
        run: |
          docker push ghcr.io/brianmmdev-that-actions/ghcr-base-image-with-dep:latest